name: Run .NET Solution, Project, Clean, Restore, Build & Publish

on:
  workflow_dispatch:
  push:
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.xaml'
    - '**.xaml.cs'
    - '**.sln'
    - '.editorconfig'
    - './.github/workflows/dotnet-tasks.yml'

jobs:
  set-git-environment:
    runs-on: ubuntu-latest
    name: Set Git environment

    steps:
      - name: Set Git environment variables
        run: |
          echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Use Git environment variables
        run: |
          echo "GIT_SHA=${GIT_SHA}"
          echo "GIT_BRANCH=${GIT_BRANCH}"

  dotnet-build-windows:
    name: Build Class Libraries on Windows Server
    runs-on: windows-latest
    needs: [set-git-environment]

    steps:
      - uses: actions/checkout@v4
      - name: Run dotnet build with CLI
        run: .\config\make.ps1 -Task Init, DotnetSolution, ProjectByModule, DotnetClean, DotnetRestore, DotnetBuild
        shell: powershell

  dotnet-build-linux:
    name: Build Class Libraries on Linux
    runs-on: ubuntu-latest
    needs: [set-git-environment]

    steps:
      - uses: actions/checkout@v4
      - name: Run dotnet build with CLI
        run: ./config/make.ps1 -Task Init, DotnetSolution, ProjectByModule, DotnetClean, DotnetRestore, DotnetBuild
        shell: pwsh

  dotnet-publish-windows:
    name: Publish Class Libraries on Windows Server
    runs-on: windows-latest
    needs: [dotnet-build-windows]

    steps:
      - uses: actions/checkout@v4
      - name: Run dotnet publish with CLI
        run: .\config\make.ps1 -Task Init, DotnetBuild, DotnetPublish
        shell: powershell

  dotnet-publish-linux:

    name: Publish Class Libraries on Linux
    runs-on: ubuntu-latest
    needs: [dotnet-build-linux]

    steps:
      - uses: actions/checkout@v4
      - name: Run dotnet publish with CLI
        run: ./config/make.ps1 -Task Init, DotnetBuild, DotnetPublish
        shell: pwsh