name: Run PowerShell Analysis & Import

on:
  workflow_dispatch:
  push:
    paths:
    - '**.ps1'
    - '**.psm1'
    - '**.psd1'
    - './.github/workflows/powershell-tasks.yml'

jobs:
  set-git-environment:
    runs-on: ubuntu-latest
    name: Set Git environment

    steps:
      - name: Set Git environment variables
        run: |
          echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Use Git environment variables
        run: |
          echo "GIT_SHA=${GIT_SHA}"
          echo "GIT_BRANCH=${GIT_BRANCH}"

  powershell-analysis-windows:
    name: Powershell analysis on Windows Server
    runs-on: windows-latest
    needs: [set-git-environment]

    steps:
      - uses: actions/checkout@v4

      - name: Run PowerShell analysis with CLI
        run: .\config\make.ps1 -Task Init, PowershellAnalysis
        shell: powershell

  powershell-analysis-linux:
    name: Powershell analysis on Linux
    runs-on: ubuntu-latest
    needs: [set-git-environment]

    steps:
      - uses: actions/checkout@v4
      - name: Run PowerShell analysis with CLI
        run: ./config/make.ps1 -Task Init, PowershellAnalysis
        shell: pwsh

  pwsh-import-windows:
    name: Import PowerShell modules on Windows Server
    runs-on: windows-latest
    needs: [powershell-analysis-windows]

    steps:
      - uses: actions/checkout@v4
      - name: Run import modules with Windows PowerShell
        run: .\config\make.ps1 -Task Init, PowershellImport
        shell: powershell

  pwsh-import-linux:
    name: Import PowerShell modules on Linux
    runs-on: ubuntu-latest
    needs: [powershell-analysis-linux]

    steps:
      - uses: actions/checkout@v4
      - name: Run import modules with PowerShell Core
        run: ./config/make.ps1 -Task Init, PowershellImport
        shell: pwsh