name: Run PowerShell Analysis & Import

on:
  workflow_dispatch:
  push:
    paths:
    - '**.ps1'
    - '**.psm1'
    - '**.psd1'
    - './github/workflows/pwsh-tasks.yml'

jobs:
  set-git-environment:
    runs-on: ubuntu-latest
    name: Set Git environment

    steps:
      - name: Set Git environment variables
        run: |
          echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Use Git environment variables
        run: |
          echo "GIT_SHA=${GIT_SHA}"
          echo "GIT_BRANCH=${GIT_BRANCH}"

  psscriptanalyzer-windows:
    name: PowerShell Code Analysis On Windows
    runs-on: windows-latest
    needs: [set-git-environment]

    steps:
      - uses: actions/checkout@v4

      - name: Run code analysis script
        run: .\config\make.ps1 -Task Init, PowershellAnalysis
        shell: powershell

  psscriptanalyzer-linux:
    name: PowerShell Code Analysis on Linux
    runs-on: ubuntu-latest
    needs: [set-git-environment]

    steps:
      - uses: actions/checkout@v4

      - name: Run code analysis script
        run: ./config/make.ps1 -Task Init, PowershellAnalysis
        shell: pwsh

  pwsh-import-windows:
    name: Import Modules on Windows Server
    runs-on: windows-latest
    needs: [psscriptanalyzer-windows]

    steps:
      - uses: actions/checkout@v4

      - name: Run import modules with Windows PowerShell
        run: .\config\make.ps1 -Task Init, PowershellImport
        shell: powershell

  pwsh-import-linux:
    name: Import Modules on Linux
    runs-on: ubuntu-latest
    needs: [psscriptanalyzer-linux]

    steps:
      - uses: actions/checkout@v4

      - name: Run import modules with PowerShell Core
        run: ./config/make.ps1 -Task Init, PowershellImport
        shell: pwsh
